# Generated by Django 2.1.7 on 2019-04-03 10:22

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('article', '0002_articlepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='content',
            field=wagtail.core.fields.RichTextField(default='a', verbose_name='Main Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlepage',
            name='feature_img',
            field=models.ForeignKey(blank=True, help_text='Feature Image of Article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='each_article_feature_img', to='wagtailimages.Image'),
        ),
    ]
