# Generated by Django 2.1.7 on 2019-04-03 11:01

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190403_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='feature_img',
            field=models.ForeignKey(blank=True, help_text='Feature Image of Article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='each_article_feature_img', to='wagtailimages.Image', verbose_name='Feature Image'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Press Enter to insert new Tag', through='article.ArticleTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
