# Generated by Django 2.1.7 on 2019-04-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190403_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='hit_count',
            field=models.IntegerField(default=0),
        ),
    ]
