# Generated by Django 2.1.7 on 2019-04-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190404_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
