# Generated by Django 2.1.7 on 2019-04-09 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('article', '0009_articlepage_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleindexpage',
            name='sidebar_form_bg',
            field=models.ForeignKey(blank=True, help_text='Background Image above sidebar form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_sidebar_form_bg', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='articleindexpage',
            name='sidebar_form_heading',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='articleindexpage',
            name='sidebar_form_main_heading',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
