# Generated by Django 2.1.7 on 2019-03-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
    ]
