# Generated by Django 2.1.7 on 2019-03-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190324_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='qt_heading',
        ),
        migrations.AddField(
            model_name='primarysitesettings',
            name='qt_heading',
            field=models.CharField(blank=True, help_text='QUOTE Heading in Pop-up form', max_length=250, null=True, verbose_name='Quote Heading'),
        ),
    ]
