# Generated by Django 2.1.7 on 2019-03-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_primarysitesettings_footer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarysitesettings',
            name='footer_logo',
            field=models.ImageField(blank=True, help_text='Footer Logo (light)', null=True, upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='primarysitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Navbar Logo (Dark). Max height fixed by CSS', null=True, upload_to='home/'),
        ),
    ]
