# Generated by Django 2.1.7 on 2019-03-24 12:33

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0007_auto_20190324_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('contact_icon', models.CharField(choices=[('fa fa-map-marker', 'Location'), ('fa fa-phone', 'Phone'), ('fa fa-envelope-o', 'E-mail'), ('fa fa-globe', 'Website')], max_length=50, verbose_name='Contact Type')),
                ('contact_url', models.URLField(max_length=255, verbose_name='Link/Url')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Contact Info',
            },
        ),
        migrations.AlterModelOptions(
            name='socialmediasettings',
            options={'verbose_name': 'Social Media'},
        ),
        migrations.AlterField(
            model_name='socialitem',
            name='sm_icon',
            field=models.CharField(choices=[('fa fa-facebook', 'Facebook'), ('fa fa-twitter', 'Twitter'), ('fa fa-skype', 'Skype'), ('fa fa-youtube', 'Youtube'), ('fa-instagram', 'Instagram'), ('fa fa-pinterest', 'Pinterest'), ('fa fa-linkedin', 'LinkedIn'), ('fa fa-envelope', 'Email')], max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='socialitem',
            name='sm_url',
            field=models.URLField(max_length=255, verbose_name='Link/Url'),
        ),
        migrations.AddField(
            model_name='contactitem',
            name='sm_settings',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_settings_panel', to='home.ContactSettings'),
        ),
    ]
