# Generated by Django 2.1.7 on 2019-03-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190324_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactitem',
            name='contact_text',
            field=models.CharField(default='sdfedf', max_length=255, verbose_name='Details'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactitem',
            name='contact_icon',
            field=models.CharField(choices=[('fa fa-map-marker', 'Location'), ('fa fa-phone', 'Phone'), ('fa fa-envelope-o', 'E-mail'), ('fa fa-globe', 'Website')], max_length=50, verbose_name='Type'),
        ),
    ]
