# Generated by Django 2.1.7 on 2019-03-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190324_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='contact_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pre-contact Text'),
        ),
    ]
