# Generated by Django 2.1.7 on 2019-03-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contactsettings_contact_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactitem',
            old_name='sm_settings',
            new_name='cnct_settings',
        ),
    ]
