# Generated by Django 2.1.7 on 2019-03-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_partnerimgsettings_partneritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneritem',
            name='alt_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
