# Generated by Django 2.1.7 on 2019-03-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_partneritem_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneritem',
            name='ptnr_url',
            field=models.URLField(default='aSDf', max_length=255, verbose_name="Pertner's website"),
            preserve_default=False,
        ),
    ]
