# Generated by Django 2.1.7 on 2019-03-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190324_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarysitesettings',
            name='copyright_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
