# Generated by Django 2.1.7 on 2019-03-31 11:33

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_homepage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='content',
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_choose',
            field=wagtail.core.fields.StreamField([('desc_n_icons', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(help_text='Small Heading', required=True)), ('description', wagtail.core.blocks.CharBlock(required=False)), ('list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('text', wagtail.core.blocks.TextBlock(max_length=200, required=True)), ('font_icon', wagtail.core.blocks.CharBlock(help_text="Icon's CSS class name", required=False))])))]))], blank=True, null=True, verbose_name='Why Choose Us?'),
        ),
    ]
