# Generated by Django 2.1.7 on 2019-03-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0018_auto_20190331_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='why_choose',
        ),
        migrations.AddField(
            model_name='homepage',
            name='test_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
