# Generated by Django 2.1.7 on 2019-03-31 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190331_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='test_img',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_bg',
            field=models.ForeignKey(blank=True, help_text='Background Image of Banner', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
