# Generated by Django 2.1.7 on 2019-03-31 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190331_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneritem',
            name='logo',
            field=models.ForeignKey(blank=True, help_text="Business partner's Logo", null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='primarysitesettings',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Icon in title bar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favicon', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='primarysitesettings',
            name='footer_logo',
            field=models.ForeignKey(blank=True, help_text='Footer Logo (light)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_logo', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='primarysitesettings',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Navbar Logo (Dark). Max height fixed by CSS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo', to='wagtailimages.Image'),
        ),
    ]
