# Generated by Django 2.1.7 on 2019-03-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190331_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partneritem',
            old_name='logo',
            new_name='partner_logo',
        ),
    ]
