# Generated by Django 2.1.7 on 2019-03-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20190331_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partneritem',
            old_name='ptnr_logo',
            new_name='logo',
        ),
    ]
