# Generated by Django 2.1.7 on 2019-04-01 08:56

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20190331_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseIconText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(help_text='Font awesome(mainly) or Flat icon CSS class name', max_length=20, verbose_name='Icon CSS Class name')),
                ('name', models.CharField(help_text="Why choose option's heading", max_length=80)),
                ('desc', models.CharField(help_text="Why choose option's description", max_length=200, verbose_name='Description')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_choose_desc',
            field=wagtail.core.fields.RichTextField(blank=True, help_text="description of 'Why choose us' section", max_length=250, null=True, verbose_name='Why Choose Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_choose_heading',
            field=models.CharField(blank=True, help_text="main heading of 'Why choose us' section", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='whychooseicontext',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='whychoose_icontext', to='home.HomePage'),
        ),
    ]
