# Generated by Django 2.1.7 on 2019-04-01 09:58

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20190401_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='why_choose_desc',
            field=wagtail.core.fields.RichTextField(blank=True, help_text="description of 'Why choose us' section", null=True, verbose_name='Why Choose Description'),
        ),
    ]
