# Generated by Django 2.1.7 on 2019-04-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20190401_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whychooseicontext',
            name='icon',
            field=models.CharField(help_text='Font awesome(mainly) or Flat icon CSS class name', max_length=50, verbose_name='Icon CSS Class name'),
        ),
    ]
