# Generated by Django 2.1.7 on 2019-04-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0027_auto_20190401_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='why_choose_img',
            field=models.ForeignKey(blank=True, help_text='Why Choose Image (Transparent Image will give satisfactory result)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='why_choose_img', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_bg',
            field=models.ForeignKey(blank=True, help_text='Background Image of Banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_bg', to='wagtailimages.Image'),
        ),
    ]
