# Generated by Django 2.1.7 on 2019-04-01 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0029_achievementcount_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='achiev_bg',
            field=models.ForeignKey(blank=True, help_text='Parallax Background image for Achievement section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_bg', to='wagtailimages.Image', verbose_name='Achievement Background Image'),
        ),
    ]
