# Generated by Django 2.1.7 on 2019-04-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_homepage_achiev_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementcount',
            name='count',
            field=models.IntegerField(help_text='Achievement counts (eg: 5000)'),
        ),
    ]
