# Generated by Django 2.1.7 on 2019-04-01 10:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20190401_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseIconText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Font awesome(mainly) or Flat icon CSS class name', max_length=50, verbose_name='Icon CSS Class name')),
                ('name', models.CharField(help_text="Option's name", max_length=80)),
                ('desc', models.CharField(help_text="Option's description", max_length=200, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='whychooseicontext',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='whychooseicontext',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='whychooseicontext',
            name='id',
        ),
        migrations.RemoveField(
            model_name='whychooseicontext',
            name='name',
        ),
        migrations.AddField(
            model_name='homepage',
            name='srvc_desc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='srvc_heading',
            field=models.CharField(blank=True, help_text='Main Heading, use <span> tag for colored text', max_length=100, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='achiev_bg',
            field=models.ForeignKey(blank=True, help_text='Parallax Background image for Achievement section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_bg', to='wagtailimages.Image', verbose_name='Background Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='why_choose_desc',
            field=wagtail.core.fields.RichTextField(blank=True, help_text="description of 'Why choose us' section", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='why_choose_heading',
            field=models.CharField(blank=True, help_text='Main Heading, use <span> tag for colored text', max_length=250, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='why_choose_img',
            field=models.ForeignKey(blank=True, help_text='Why Choose Image (Transparent Image will give satisfactory result)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='why_choose_img', to='wagtailimages.Image', verbose_name='Side Image'),
        ),
        migrations.AddField(
            model_name='whychooseicontext',
            name='baseicontext_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.BaseIconText'),
            preserve_default=False,
        ),
    ]
