# Generated by Django 2.1.7 on 2019-04-01 10:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20190401_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesIconText',
            fields=[
                ('baseicontext_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.BaseIconText')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_icontext', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('home.baseicontext', models.Model),
        ),
    ]
