# Generated by Django 2.1.7 on 2019-04-02 07:08

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0033_servicesicontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=50)),
                ('desc', wagtail.core.fields.RichTextField(verbose_name='Description')),
                ('facilities', wagtail.core.fields.StreamField([('facility', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='White colored image preferred', required=True)), ('desc', wagtail.core.blocks.TextBlock(max_length=500, required=True, verbose_name='Description'))]))], blank=True, null=True, verbose_name='Insurance Facilities')),
                ('img', models.ForeignKey(blank=True, help_text='Image Besides Insurance Policy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image', verbose_name='Side Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='ins_desc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ins_heading',
            field=models.CharField(blank=True, help_text='Main Heading, use <span> tag for colored text', max_length=100, null=True, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ins_policy', to='home.HomePage'),
        ),
    ]
