# Generated by Django 2.1.7 on 2019-04-02 09:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0035_simplepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplepage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Main Content'),
        ),
        migrations.AddField(
            model_name='simplepage',
            name='heading_bg',
            field=models.ForeignKey(blank=True, help_text='Background Image in Heading/Title', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heading_bg', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='simplepage',
            name='slogan_img',
            field=models.ForeignKey(blank=True, help_text='Slogan Background Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slogan_img', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='simplepage',
            name='slogan_txt',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Slogan Text'),
        ),
    ]
