# Generated by Django 2.1.7 on 2019-04-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20190402_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarysitesettings',
            name='txt_ph_nmb_footer',
            field=models.CharField(blank=True, help_text='Text below phone number in Footer', max_length=150, null=True, verbose_name='Text below Phone No.(bottom)'),
        ),
    ]
