# Generated by Django 2.1.7 on 2019-04-07 09:47

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_primarysitesettings_txt_ph_nmb_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarysitesettings',
            name='qt_disclaimer',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Quote Disclaimer in pop-up form (<span>, <p> & <a> tags are colored)', null=True, verbose_name='Quote Disclaimer'),
        ),
    ]
