# Generated by Django 2.1.7 on 2019-04-09 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0039_auto_20190407_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='prom_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promote_article', to='wagtailcore.Page', verbose_name='Article Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='prom_custom_desc',
            field=models.TextField(blank=True, help_text='Description if no article chosen', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='prom_custom_heading',
            field=models.CharField(blank=True, help_text='Heading if no article chosen, use <span> tag for colored text', max_length=150, null=True, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='prom_custom_url',
            field=models.URLField(blank=True, help_text='Custom Url if no article chosen', null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='prom_custom_url_text',
            field=models.CharField(blank=True, help_text='Custom url text if no article chosen', max_length=150, null=True, verbose_name='URL Text'),
        ),
    ]
