# Generated by Django 2.1.7 on 2019-04-09 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20190409_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='prom_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promote_article', to='article.ArticlePage', verbose_name='Article Page'),
        ),
    ]
