# Generated by Django 2.1.7 on 2019-04-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20190409_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='prom_custom_heading',
            field=models.CharField(blank=True, help_text='Heading if no article chosen', max_length=150, null=True, verbose_name='Heading'),
        ),
    ]
