# Generated by Django 2.1.7 on 2019-04-10 07:55

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20190410_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='home.QuoteFormPage'),
        ),
    ]
