# Generated by Django 2.1.7 on 2019-04-15 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0046_auto_20190410_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='keywords',
            field=models.TextField(blank=True, help_text='comma separated', null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Open Graph Meta Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image', verbose_name='Open Graph Meta Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Open Graph Meta Title'),
        ),
        migrations.AddField(
            model_name='simplepage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='simplepage',
            name='keywords',
            field=models.TextField(blank=True, help_text='comma separated', null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='simplepage',
            name='og_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Open Graph Meta Description'),
        ),
        migrations.AddField(
            model_name='simplepage',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image', verbose_name='Open Graph Meta Image'),
        ),
        migrations.AddField(
            model_name='simplepage',
            name='og_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Open Graph Meta Title'),
        ),
    ]
