# Generated by Django 2.1.7 on 2019-04-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20190415_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
