# Generated by Django 2.1.7 on 2019-04-15 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0050_homepage_tm_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteformpage',
            name='bg_img',
            field=models.ForeignKey(blank=True, help_text='Quote form page Background image', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image', verbose_name='Background Image'),
        ),
    ]
