# Generated by Django 2.1.7 on 2019-04-15 10:18

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_quoteformpage_bg_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='txt_desc',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='txt_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Heading'),
        ),
    ]
