# Generated by Django 2.1.7 on 2019-04-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_auto_20190421_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactitem',
            name='contact_url',
            field=models.CharField(max_length=255, verbose_name='Link/Url'),
        ),
    ]
