# Generated by Django 2.1.7 on 2019-04-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_auto_20190424_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarysitesettings',
            name='qt_slogan',
        ),
    ]
