# Generated by Django 2.1.7 on 2019-04-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_remove_primarysitesettings_qt_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseicontext',
            name='desc',
            field=models.TextField(help_text="Option's description", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='baseicontext',
            name='icon',
            field=models.CharField(help_text='Font awesome(mainly) or Flat icon CSS class name', max_length=100, verbose_name='Icon CSS Class name'),
        ),
        migrations.AlterField(
            model_name='baseicontext',
            name='name',
            field=models.CharField(help_text="Option's name", max_length=250),
        ),
    ]
