# Generated by Django 2.1.7 on 2019-04-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_auto_20190428_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='srvc_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
