# Generated by Django 2.1.7 on 2019-04-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_auto_20190428_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplepage',
            name='template_string',
            field=models.CharField(choices=[('home/simple_single_pages/medicare_advantage.html', 'Medicare Advantage'), ('home/simple_single_pages/medigap.html', 'Medigap'), ('home/simple_single_pages/critical_illness.html', 'Critical Illness'), ('home/simple_single_pages/dental_vision.html', 'Dental Vision'), ('home/simple_single_pages/social_security.html', 'Social Security'), ('home/simple_single_pages/low_income.html', 'Low Income')], default='home/simple_page.html', max_length=255),
        ),
    ]
