#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source $DIR/config.sh


OS="$(uname -s)"

if [ $OS == "Darwin" ]; then
    dropdb $DBNAME
else
sudo -u postgres bash << EOF
    echo "DB User Password: $DBPASS"
    dropdb -U $DBUSER -W $DBNAME
EOF
fi
